apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: spring-study-ks
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./luoquanhong/springstudy-mainfest
  prune: true
  sourceRef:
    kind: GitRepository
    name: spring-study-gitrepo
  validation: client