apiVersion: v1
kind: Service
metadata:
  name: customctomcat-service
  namespace: default
  labels:
    app : customtomcat
spec:
  selector:
    app : customtomcat
  type: NodePort
  ports:
    - name: web
      port: 8380
      targetPort: 8080
      nodePort: 30003

